spring.application.name=urlShortner
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


server.servlet.context-path=/url-shortner

app.base-url=http://localhost:8080/url-shortner/
url.expiry.days=30